
POST http://localhost:3000/users/register
Content-Type: application/json

{
"username":"flash@dominio.es", "password":"man$Super3"
}
####

POST http://localhost:3000/users/login
Content-Type: application/json

{
"username":"flash@dominio.es", "password":"man$Super3"
}
####

POST http://localhost:3000/users/profiledata
Content-Type: application/json

{
"username":"flash@dominio.es", "profiledata":{
    "city":"Barcelona",
    "region":"Barcelona",
    "zip":"08032"
    }
}

####
GET http://localhost:3000/users/flash@dominio.es

###
POST http://localhost:3000/users/user
Content-Type: application/json

{
"username":"flash@dominio.es"
}